spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
  data:
    redis:
      host: localhost
      port: 6379
      password: root@123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    password: 123456
    username: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true

